### ISSUE TITLE
🔖 Feature: Add Button

### ISSUE THREAD

**Issue by nishitxmehta** [nishitxmehta/PortfolioWebsite#1]
### 🔖 Feature description
Add a button in place of LinkedIn icon as shown below:

![Screenshot](https://github.com/nishitxmehta/nishitmehta-portfolio/assets/80708599/3ab9b25e-a43a-4b27-bc5a-16fbd2e5f2c1)

It would be nice if the button displays a text `Download Resume` with an `arrow-down` icon and hovering effect similar to the `Contact Me` button.

### 👀 Have you spent some time to check if this issue has been raised before?
 - [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?
- [x] I have read the [Code of Conduct](https://github.com/nishitxmehta/nishitmehta-portfolio/blob/main/CODE_OF_CONDUCT.md)

**Comment by Bitnagar** [comment]
Can i work on this issue? Please assign this to me.

**Comment by nishitxmehta** [comment]
Sure @Bitnagar, I've assigned it you, go ahead!

**Comment by nishitxmehta** [comment]
@Bitnagar here's resume link: https://drive.google.com/drive/folders/1xg2cpODg3CSDXdKJVUhdW7q4Q0yOG3TY

**Comment by nishitxmehta** [comment]
@Bitnagar here's link to my resume: https://drive.google.com/file/d/10w1btFvGA5B0mDBppTNzdHDMR6P0Uhmx/view?usp=drive_link

Inside the `assets` folder, make a folder `pdf` and add my resume in it.

**Comment by nishitxmehta** [comment]
@Bitnagar here's link to my resume: https://drive.google.com/file/d/10w1btFvGA5B0mDBppTNzdHDMR6P0Uhmx/view?usp=drive_link

Inside the `assets` folder, make a folder `pdf` and add my resume in it.
Link this location to the button.

**Comment by nishitxmehta** [comment]
@Bitnagar here's link to my resume: https://drive.google.com/file/d/10w1btFvGA5B0mDBppTNzdHDMR6P0Uhmx/view?usp=drive_link

Inside the `assets` folder, make a folder `pdf` and add my resume in it.
Link this path to the button.
