### ISSUE TITLE
🐛 Bug Report: Responsiveness Issue

### ISSUE THREAD

**Issue by nishitxmehta** [nishitxmehta/PortfolioWebsite#3]
### 🐛 Bug description
Responsiveness issue arises in width: (341px - 453px) & (576px - 1150px) for **buttons** in `About Me` section.

**It would be nice** 
- If **buttons** in `About Me` section for width: (341px - 453px) look like

![Sceenshot_1](https://github.com/nishitxmehta/nishitmehta-portfolio/assets/80708599/dfcc955a-973a-44b5-9016-3c5df158c081)

- If **buttons** in `About Me` section for width: (576px - 1150px) look like

![Screenshot_2](https://github.com/nishitxmehta/nishitmehta-portfolio/assets/80708599/9cae44bf-7b74-49e9-9e8e-914c3bd97c48)

### 👀 Have you spent some time to check if this issue has been raised before?
 - [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?
- [x] I have read the [Code of Conduct](https://github.com/nishitxmehta/nishitmehta-portfolio/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhaygzb15** [comment]
Hey!! Can I work on upgrading the CSS for this repo? I have some experience in UI/UX.

**Comment by nishitxmehta** [comment]
@abhaygzb15 I've assigned you, go ahead!

**Comment by nishitxmehta** [comment]
any update @abhaygzb15 ?

**Comment by Chayandev** [comment]
hey @nishitxmehta I don't think still you have this responsiveness issue, I can see that u got the responsiveness You are asking for. I not please elaborate more about the issue else you can close this issue.

**Comment by nishitxmehta** [comment]
Hi @Chayandev, this responsiveness issue is still there. Read the bug description carefully to be precise the `It would be nice` section. In that section its clearly mentioned at what **width range** the issue is coming and how those buttons should look like in that **width range**. Just do inspect, at that width range, you'll get to see yourself.
I hope you have understood! If not feel free to ask.

**Comment by Chayandev** [comment]
ok I got the issue, I want to work on that, please assign me this.

**Comment by nishitxmehta** [comment]
@Chayandev, go ahead, I've assigned you the issue.
